spring.datasource.url=jdbc:postgresql://localhost:5432/blocnotes_app
spring.datasource.username=postgres
spring.datasource.password=Ahitamamba02!
spring.datasource.driver-class-name=org.postgresql.Driver